### ISSUE TITLE
MemoryStore doesn't save ES2015/ES6 Map objects correctly

### ISSUE THREAD

**Issue by AMA3** [roccomuso/memorystore#6]
When I add a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object to the session, subsequent requests find an empty object under the same name instead of the original Map. This results in an error.
```
var express = require('express');
var app = express();
var session = require('express-session')
var MemoryStore = require('memorystore')(session)
app.use(session({
  store: new MemoryStore({ checkPeriod: 86400000 }),
  resave: true,
  saveUninitialized: true,
  secret: 'keyboard cat'
  }));
app.get( '/', ( req, res ) => {
  if ( ! req.session.hasOwnProperty( 'mymap' ) )
    req.session.mymap = new Map( [ [ 'message', 'hello' ] ] );
  console.log( req.session.mymap );
  res.end( req.session.mymap.get('message') )
  } );
app.listen( 8100, () => console.log('Go ahead; I\'m listening.' ) );
```
First Request (console):
> Go ahead; I'm listening.
> Map { 'message' => 'hello' }

First Request (browser):
> hello

Second Request (console):
>**TypeError: req.session.mymap.get is not a function**
>    **at app.get (.../app.js:15:30)**
>    **at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)**
>    **at next (.../node_modules/express/lib/router/route.js:137:13)**
>    **at Route.dispatch (.../node_modules/express/lib/router/route.js:112:3)**
>    **at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)**
>    **at .../node_modules/express/lib/router/index.js:281:22**
>    **at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)**
>    **at next (.../node_modules/express/lib/router/index.js:275:10)**
>    **at Immediate.<anonymous> (.../node_modules/express-session/index.js:489:7)**
>    **at runCallback (timers.js:697:11)**
>{}

Second Request (browser):
>TypeError: req.session.mymap.get is not a function
>    at app.get (.../app.js:15:30)
>    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
>    at next (.../node_modules/express/lib/router/route.js:137:13)
>    at Route.dispatch (.../node_modules/express/lib/router/route.js:112:3)
>    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
>    at .../node_modules/express/lib/router/index.js:281:22
>    at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)
>    at next (.../node_modules/express/lib/router/index.js:275:10)
>    at Immediate.<anonymous> (.../node_modules/express-session/index.js:489:7)
>    at runCallback (timers.js:697:11)

I'm using:
>"express": "~4.16.0",
>"express-session": "^1.15.6",
>"memorystore": "^1.6.0",

See also: [expressjs/session: es2015 Map object looks problem #302](https://github.com/expressjs/session/issues/302)

**Comment by AMA3** [comment]
Thanks for the response. I'm using Node 10.1.0... dunno if that has anything to do with it.  What behavior do you get?  In any event I can see that the JSON.stringify/parse limitation could be causing this.  Perhaps you should mention it in the readme, either in the introductory paragraphs or under the serializer option explanation?

**Comment by gmcdev** [comment]
Agree with OP -- trying to save a Promise to the store also results in an empty object. May not be within the design spec, but should definitely note that the store must be pure JSON.

**Comment by HunteRoi** [comment]
It would be good to use a work-around to JSONize ES6 Map objects. A simple one is to change the map to an array of arrays containing key-value pair as the constructor of the Map object can take an array of key-value pairs as parameter:
```js
var map = new Map("someKey", { anotherKey: "someValue" });
var jsonizedMap = JSON.stringify([...map]);
var parsedMap = new Map(JSON.parse(jsonizedMap));
```

Source : https://2ality.com/2015/08/es6-map-json.html
